rabbitmq:
  image: "rabbitmq:3-management"
  hostname: "my-rabbit"
  labels:
    name: "some-rabbit"
  ports:
  - "15672:15672"
  - "3131:5672"
configserver:
  image: "eso31/springimage"
  ports:
  - "8888:8888"