server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost/skytask
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    generate-ddl: true

  rabbitmq:
    host: localhost
    port: 3131
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
